Description: >
  Adri Forczek / Udemy Test for CloudFormation

# only required section
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0713f98de93617bb4
      InstanceType: t2.micro # included in aws free tier
      SecurityGroupIds:
        # short format: - !Ref WebServerSecurityGroup
        # longer format: 
        - 
          Ref: WebServerSecurityGroup
      Tags:
        -
          Key: Name
          Value: Web Server # this can be anything
        - 
          Key: Project
          Value: CloudFormation Step By Step

  WebServerSecurityGroup:
    # use VpcId to specify for which VPC to create the security group
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web servers
      # ingress specifies an inbound rule for a security group
      SecurityGroupIngress:
        - 
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: Name
          Value: Web Server Security Group
